FromDoppler/emms25

components/ecommerce/pre/doppler-academy-banner.php, components/navbar.php, pages/ecommerce/pre/home-registrado.php, registrado.php, src/1.0.0/css/components/doppler-academy-banner.css
new register home
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5494)
=> DS-5494 register home

.docker/db/EMMS25.sql
https://makingsense.atlassian.net/browse/DS-5492
=> DS-5492 sql emms25

components/academyBanner.php, components/sponsors/libraryResources/academyBanner.php, components/sponsors/libraryResources/conferences.php, components/sponsors/libraryResources/hero.php, components/sponsors/libraryResources/registerModal.php, components/sponsors/libraryResources/sponsorsList.php, pages/sponsors/library-resources.php, sponsors.php
https://makingsense.atlassian.net/browse/DS-5526
=> DS-5526 refactor sponsors page

components/ecommerce/pre/ecommerce/hello-module.php, components/ecommerce/pre/ecommerce/hello-vip-module.php, pages/ecommerce/pre/ecommerce-registrado.php, src/1.0.0/css/components/hero-registration.css, src/1.0.0/css/components/speakers-list.css, src/1.0.0/css/pages/digital-trends.css, src/1.0.0/css/pages/ecommerce.css, src/1.0.0/css/pages/sponsors-promo.css
add new ecommerce logged UI
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5496)
=> DS-5496 commerce logged

components/sponsors/libraryResources/hero.php, components/sponsors/libraryResources/sponsorsList.php, pages/sponsors/library-resources.php, sponsors-interna.php, sponsors-promo.php, sponsors-registrado.php, src/1.0.0/js/sponsorsPromo.js
https://makingsense.atlassian.net/browse/DS-5526
=> DS-5526 refactor sponsors, sponsors interna & promo

utils/Relay.php
add new config for earlybirds ecommerce email
Related to: [Ticket ](https://makingsense.atlassian.net/browse/DS-5502)
=> DS-5502 config earlybirds ecommerce email

components/academyBanner.php, components/ecommerce/pre/doppler-academy-banner.php, components/ecommerce/pre/home/hello-module.php, components/ecommerce/pre/speakers-carousel.php, components/ecommerce/pre/users-comments.php, components/event-card.php, components/footer.php, components/navbar-reg.php, components/sponsors/libraryResources/academyBanner.php, ecommerce-registrado.php, ecommerce.php, ediciones-anteriores-registrado.php, index.php, pages/ecommerce/pre/ecommerce-registrado.php, registrado.php, sponsors-promo.php, src/1.0.0/css/components/doppler-academy-banner.css, src/1.0.0/css/components/frequent-questions.css, src/1.0.0/css/pages/sponsors.css
apply final content and visual fixes
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5503)
=> DS-5503 apply final content

components/sponsors/libraryResources/conferences.php
[DS-5532](https://makingsense.atlassian.net/browse/DS-5532)
[DS-5532]: https://makingsense.atlassian.net/browse/DS-5532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-5532 fix & refactor conferences sponsors

src/1.0.0/js/commonAnimations.js
https://makingsense.atlassian.net/browse/DS-5529
=> DS-5529  flicktify

ediciones-anteriores.php
https://makingsense.atlassian.net/browse/DS-5553
=> DS-5553 ediciones anteriores

components/gtm.php, components/head.php, config.php
https://makingsense.atlassian.net/jira/software/projects/DS/boards/21?selectedIssue=DS-5534
=> DS-5534 gtm refactor & hotjar

pages/ecommerce/pre/ecommerce-registrado.php, pages/ecommerce/pre/ecommerce.php, pages/ecommerce/pre/home-registrado.php, pages/ecommerce/pre/home.php, pages/sponsors/library-resources.php, sponsors-interna.php, sponsors-promo.php
https://makingsense.atlassian.net/browse/DS-5546
=> DS-5546 remove gtm from qa env

components/ecommerce/pre/home/hello-module.php, components/sponsors/libraryResources/conferences.php, components/sponsors/libraryResources/registerModal.php, components/sponsors/libraryResources/sponsorsList.php, ecommerce-registrado.php, ecommerce.php, ediciones-anteriores-registrado.php, ediciones-anteriores.php, index.php, pages/sponsors/library-resources.php, registrado.php, services/register.php, sponsors-registrado.php, sponsors.php
https://makingsense.atlassian.net/browse/DS-5554
=> DS-5554 refactor isRegistered

components/ecommerce/pre/register-form.php, components/sponsors/libraryResources/registerModal.php, components/sponsorsList.php, ediciones-anteriores.php, pages/sponsors/library-resources.php
https://makingsense.atlassian.net/browse/DS-5557
=> DS-5557 sponsors fix register modal

sponsors-promo.php
add block id
Related to: [ticket](https://makingsense.atlassian.net/browse/DS-5561)
=> DS-5561 add block id

config.php, services/register.php, services/restrictOriginAccess.php
https://makingsense.atlassian.net/browse/DS-5562
=> DS-5562 refactor register flow security

services/EmailService.php, services/clearCache.php, services/functions.php, services/getCountryNameAndCode.php, services/getLogErrors.php, services/getMediaPartners.php, services/getPhase.php, services/getRegisteredByEmail.php, services/getSubscriptionsDoppler.php
[DS-5570-restrict-origin-accesss-on-services](https://makingsense.atlassian.net/browse/DS-5570)
=> DS-5570 restrict origin in services

services/EmailService.php, services/clearCache.php, services/functions.php, services/getCountryNameAndCode.php, services/getLogErrors.php, services/getMediaPartners.php, services/getPhase.php, services/getRegisteredByEmail.php, services/getSubscriptionsDoppler.php, services/register.php
https://makingsense.atlassian.net/browse/DS-5570
=> DS-5570 remove restrict from services

components/sponsors/libraryResources/resources/resourceGrid.php
change resources link
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5549)
=> DS-5549 change resources link

checkout-success.php, checkout.php, components/checkout/checkout-success.php, components/checkout/checkout.php, components/checkout/faq.php, config.php, pages/checkout/checkout-success.php, pages/checkout/checkout.php
https://makingsense.atlassian.net/browse/DS-5581
=> DS-5581 refactor checkout components & pages

components/ecommerce/pre/companies-list.php, components/ecommerce/pre/ecommerce/entry-plans.php, components/ecommerce/pre/ecommerce/hello-vip-module.php, components/ecommerce/schedule/mobile-carousel.php, components/ecommerce/schedule/schedule.php, components/sponsorsList.php, pages/ecommerce/pre/ecommerce-registrado.php, src/1.0.0/css/components/companies-list.css, src/1.0.0/css/general/constants.css, src/1.0.0/js/toggleVipElements.js
apply pre deploy final adjustments
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5590)
=> DS-5590 pre deploy adjustments

utils/EmailTemplateManager.php, utils/relay-templates/ecommerce/ecommerce-pre-template.html, utils/relay-templates/ecommerce/ecommerce-vip-template.html
add pre and vip ecommerce emails
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5589)
=> DS-5589 email pre vip

services/register.php
https://makingsense.atlassian.net/browse/DS-5595
=> DS-5595 fix utms register free

src/1.0.0/js/common/submitForm.js, src/1.0.0/js/common/submitHelpers.js, src/1.0.0/js/common/switchForm.js
Se realizó una refactorización del archivo `submitForm.js` con el objetivo de mejorar la legibilidad, reducir la duplicación de código y separar responsabilidades.
- Se extrajeron funciones como `buildUserData`, `extractFormData`, `setEventInLocalStorage`, `toggleButtonLoading` y `trackMetaPixelRegistration` al nuevo módulo `submitHelpers.js`.
- Se creó la función `sendUserData` para unificar el `fetch` tanto de `submitFormFetch` como de `submitWithoutForm`.
- Se simplificó y limpió el archivo original `submitForm.js`.
- Mayor separación de responsabilidades.
- Código más mantenible y testeable.
- Reutilización de lógica entre formularios con y sin campos visibles.
[DS-5599](https://makingsense.atlassian.net/browse/DS-5599)
[DS-5599]: …
=> DS-5599 refactor move form submission logic to submitHelpers.js

src/1.0.0/js/common/submitForm.js, src/1.0.0/js/common/submitHelpers.js
Implements Meta Pixel event tracking for successful user registrations.
Adds trackMetaPixelRegistration helper function.
Triggers Meta Pixel event CompleteRegistration after a successful response from the backend.
🔗 Related to [DS-5601](https://makingsense.atlassian.net/browse/DS-5601)
This allows the marketing team to track conversions and campaign performance more accurately.
[DS-5601]: https://makingsense.atlassian.net/browse/DS-5601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DS-5601] add Meta Pixel tracking on successful registration

utils/relay-templates/ecommerce/ecommerce-pre-template.html
chore: change email links
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5606)
=> DS-5606 change email links

utils/relay-templates/ecommerce/ecommerce-vip-template.html
update email vip to v2
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5605)
=> DS-5605 email vip v2

components/ecommerce/during/ecommerce/hello-vip-module.php, components/ecommerce/pre/ecommerce/hello-vip-module.php
https://makingsense.atlassian.net/browse/DS-5598
=> DS-5598 change content

components/checkout/checkout-success.php, components/ecommerce/during/central-video.php, components/ecommerce/during/ecommerce/event-live.php, components/ecommerce/during/ecommerce/vip-features.php, components/ecommerce/during/hellobar-vip.php, components/ecommerce/during/hellobar.php, components/ecommerce/during/home/hello-module.php, components/ecommerce/during/premium-content.php, components/ecommerce/during/register-form.php, components/ecommerce/during/speakers-carousel.php, components/ecommerce/pre/ecommerce/entry-plans.php, components/event-card.php, components/register-form-component.php, pages/ecommerce/during/home-registrado.php, pages/ecommerce/during/home.php, src/1.0.0/css/components/event-cards.css, src/1.0.0/css/components/hero-conference.css, src/1.0.0/css/components/hero-registration.css, src/1.0.0/css/components/premium-content-banner.css
apply final ux adjustments
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5616)
=> DS-5616 final ux adjustments

utils/relay-templates/ecommerce/ecommerce-during-vip-template.html
add during email vip
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5615)
=> DS-5615 during email vip

utils/relay-templates/ecommerce/ecommerce-during-template.html
add during email free
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5614)
=> DS-5614 during free email

utils/relay-templates/ecommerce/workshop/ecommerce-certificate-joseanmuñoz.html, utils/relay-templates/ecommerce/workshop/ecommerce-certificate-laurabarreto.html, utils/relay-templates/ecommerce/workshop/ecommerce-certificate-luisbetancourt.html, utils/relay-templates/ecommerce/workshop/ecommerce-certificate-matiascarrera.html, utils/relay-templates/ecommerce/workshop/ecommerce-certificate-pablomoratinos.html, utils/relay-templates/ecommerce/workshop/ecommerce-certificate-xavierIdevik.html
add workshops emails
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5612)
=> DS-5612 workshops emails

components/ecommerce/post/central-video.php, components/ecommerce/post/ecommerce/hello-module.php, components/ecommerce/post/ecommerce/hello-vip-module.php, components/ecommerce/post/ecommerce/seo-reg.php, components/ecommerce/post/ecommerce/seo-unreg.php, components/ecommerce/post/ecommerce/video-ticketing.php, components/ecommerce/post/ecommerce/vip-features.php, components/ecommerce/post/home/hello-module.php, components/ecommerce/post/home/seo-reg.php, components/ecommerce/post/home/seo-unreg.php, components/ecommerce/post/register-form.php, components/ecommerce/post/register-withoutform.php, components/ecommerce/post/speaker-interna/event-recorded.php, components/ecommerce/post/speaker-interna/promo-vip.php, components/ecommerce/post/speakers-carousel.php, pages/ecommerce/post/ecommerce-registrado.php, pages/ecommerce/post/ecommerce.php, pages/ecommerce/post/home-registrado.php, pages/ecommerce/post/home.php, pages/ecommerce/post/speaker-interna.php
https://makingsense.atlassian.net/browse/DS-5608
=> DS-5608 init post

src/1.0.0/css/components/schedule/speaker-card/speaker-card.css
change mobile height in speaker card
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5620)
=> DS-5620 fix mobile speaker card

components/ecommerce/during/ecommerce/certificate/certificate.js, descarga-certificado.php, src/1.0.0/js/certificateWorkshop.js
fix certificate workshops
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5621)
=> DS-5621 certificate  script

components/ecommerce/during/ecommerce/event-live.php, src/1.0.0/css/components/hero-conference.css
https://makingsense.atlassian.net/browse/DS-5619
=> DS-5619 reprogramado transition workshops

utils/EmailTemplateManager.php, utils/relay-templates/ecommerce/ecommerce-post-vip-template.html
add ecommerce vip template
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5625)
=> DS-5625 email post

utils/relay-templates/ecommerce/ecommerce-post-template.html
add ecommerce post email free
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5624)
=> DS-5624 email free post

components/schedule/speaker-card/speaker-button.php
=> DS-5623 ecommerce post

components/ecommerce/post/speaker-interna/event-recorded.php, src/1.0.0/css/components/ecommerce/speaker-interna/event-recorded.css, src/1.0.0/css/styles.css
https://makingsense.atlassian.net/browse/DS-5628
=> DS-5628 Adjust internal speaker layout and spacing

components/checkout/checkout-success.php, components/schedule/speaker-grid/grid-days.php, pages/ecommerce/post/ecommerce-registrado.php, src/1.0.0/css/pages/checkout.css
post deploy changes
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5626)
=> DS-5626 adjustments post deployment changes

components/ecommerce/post/home/hello-module.php, components/ecommerce/post/register-form.php, src/1.0.0/css/components/hero-registration.css
feat: update content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5685)
=> DS-5685 update content

package.json
https://makingsense.atlassian.net/browse/DS-5686
=> DS-5686 update scripts

components/ecommerce/post/users-comments.php
add structure data for quotes
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5728)
=> DS-5728 add structure data for quotes

components/digital-trends/pre/home/hello-module.php, components/ecommerce/during/home/hello-module.php, components/ecommerce/post/home/hello-module.php, components/ecommerce/pre/home/hello-module.php, src/1.0.0/css/pages/home.css
rename css to bem
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5738)
=> DS-5738 rename css to bem

index.php, pages/digital-trends/pre/home-registrado.php, pages/digital-trends/pre/home.php, registrado.php
change routes paths
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5735)
=> DS-5735 fix- paths

config.php, services/getCurrentEvent.php
https://makingsense.atlassian.net/browse/DS-5743
=> DS-5743 refactor: add dynamic event configuration structure & service

digital-trends-registrado.php, digital-trends.php, index.php, registrado.php
https://makingsense.atlassian.net/browse/DS-5753
=> DS-5753 Refactor: new router system apply Home DT

speaker-interna.php, sponsors-interna.php, sponsors-registrado.php, sponsors.php
https://makingsense.atlassian.net/browse/DS-5754
=> DS-5754 Refactor: new router system apply SPONSORS SPEAKERS

ediciones-anteriores-registrado.php, ediciones-anteriores.php
add new previous edition
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5750)
=> DS-5750 new previous edition

pages/digital-trends/pre/digital-trends-registrado.php
disabled referral block
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5756)
=> DS-5756 disabled referal block

utils/relay-templates/dt/dt-pre-template.htm
add dplrid id to url
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5723)
=> DS-5723 fix email template 

components/referral.php, pages/digital-trends/pre/digital-trends-registrado.php
https://makingsense.atlassian.net/browse/DS-5724
- Implementa el sistema de referidos EMMS con enlace UTM usando el email ya codificado.  
- Permite copiar el enlace de referido directamente desde la página de registro y pre-registro.
=> DS-5724 UTM tracking with encoded email

components/sponsors-promo/hero.php
change button
Related to: [Ticket ](https://makingsense.atlassian.net/browse/DS-5788)
=> DS-5787 sponsors pre dt

stripe/controllers/StripeCustomersController.php, stripe/createCustomer.php, stripe/models/SubscriberDopplerList.php, stripe/utils/SpreadSheetGoogle.php, utils/EmailTemplateManager.php, utils/relay-templates/dt/dt-pre-vip-template.html
- Conversión de flujo Ecommerce a Digital Trends VIP
- Actualización de listas Doppler y Spreadsheets
-  Mejoras en manejo de errores y logging
- Template de email específico para Digital Trends Vip
- Mantenimiento de funcionalidad existente
=> DS-5789 digital trends vip purchase processing

utils/SpreadSheetGoogle.php
=> DS-5779 remove fields

src/1.0.0/js/autoCompleteUserForm.js
- Se agrega autocompletetado para multiples formularios existentes en una misma pagina.
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5824)
=> DS-5824 autocomplete multiple forms

.docker/config/php/Dockerfile, .docker/db/EMMS25.sql, .docker/docker-compose.yml, .docker/readme.md, config.php, config/redis.php, stripe/controllers/StripeCustomersController.php, stripe/createCustomer.php, stripe/models/RegisteredDatabase.php, stripe/models/StripeCustomersDatabase.php, stripe/models/StripeCustomersJobsDatabase.php, stripe/models/SubscriberDopplerList.php, stripe/workers/EmailWorker.php, stripe/workers/ListWorker.php, stripe/workers/README.md, stripe/workers/SpreadsheetWorker.php, stripe/workers/core/BaseWorker.php, stripe/workers/core/RedisManager.php, utils/Logger.php
Se implementa un sistema de colas basado en Redis Streams para procesar suscripciones VIP de forma asíncrona, mejorando la escalabilidad y resiliencia del flujo de Stripe.
Actualmente, el procesamiento era síncrono y ejecutaba en serie:
1. Envío de email
2. Guardado en Google Sheets
3. Agregado a lista Doppler
Problemas:
- Tiempos de respuesta lentos (3-5s)
- Fallas en cascada si un servicio falla
- Escalabilidad limitada
- Sin retry automático
Arquitectura de **workers asíncronos** con Redis Streams:
Webhook Stripe → Controller → Redis Streams → Workers (Email / Spreadsheet / Doppler)
↓ ↓
DB (sync) Servicios externos (async)
**Componentes:**
1. Controller refactorizado: guarda en DB y encola jobs en Redis.
2. 3 Workers especializados:
- `EmailWorker`
- `SpreadsheetWorker`
- `ListWorker` …
=> DS-5832 Sistema de colas con Redis Streams para procesamiento asíncrono de suscripciones VIP

components/checkout-lp/checkout-success.php, components/modal/partials/modal-vip.php, components/schedule/schedule-tabs/schedule-button.php, components/schedule/schedule-tabs/schedule-tabs-helper.php, components/schedule/schedule.php, components/schedule/speaker-card/speaker-ribon.php, components/schedule/speaker-grid.php, pages/checkout-lp/checkout-success.php, pages/checkout-lp/checkout.php, pages/checkout-lp/components/entry-plans.php, pages/checkout-lp/components/grid-event-types.php, pages/checkout-lp/components/hello-module.php, pages/checkout-lp/components/video-ticketing.php, pages/checkout-lp/components/vip-features.php, pages/checkout-lp/landing.php, src/1.0.0/css/components/prices-plans.css, src/1.0.0/css/components/schedule/speaker-card/speaker-ribon.css
- Se agrega la UX y las modificaciones de componentes para todo el nuevo flujo de landing checkout
Related to : [Ticket](https://makingsense.atlassian.net/browse/DS-5836)
=> DS-5836 landing checkout ux

components/checkout-lp/checkout-success.php, components/checkout-lp/checkout.php, components/checkout/checkout.php, pages/checkout-lp/checkout.php, pages/checkout/checkout-success.php, pages/checkout/checkout.php, services/create-checkout-session.php, services/fetch-session-status.php
Mejoras
- Migración de páginas desde `ecommerce` a `digital-trends`.
- Implementación de Stripe Embedded Checkout (`checkout-lp/checkout.php`).
- Nueva lógica de `checkout-success` con almacenamiento local y manejo de errores.
- Simplificación de `create-checkout-session.php` (email opcional).
- Incorporación de caching con Memcached y TTL en `fetch-session-status.php`.
- Se añade encabezado `Content-Type: application/json` y control de timeout.
https://makingsense.atlassian.net/browse/DS-5839
=> DS-5839 Integrate Stripe checkout flow and backend caching improvements

components/schedule/speaker-card/helpers/speaker-button.php, components/schedule/speaker-card/speaker-button.php
- Se remueve el boton de la card de speakers no relacionados a workshops cuando se encuentra en la landing de checkout
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5841)
=> DS-5841 remove speaker buttons

components/checkout-lp/checkout-success.php, pages/checkout-lp/checkout-success.php
fix checkout-success instegration
https://makingsense.atlassian.net/browse/DS-5839
=> DS-5839 fix checkout-success instegration
